# Generated by Django 4.2.1 on 2023-05-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('us', 'USA'), ('jp', 'Japan'), ('uk', 'United Kingdom'), ('sz', 'SWITZERLAND')], max_length=5),
        ),
    ]
