# Generated by Django 4.2.1 on 2023-09-19 08:14

import app_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_companycruisemodel_rename_companyfield_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecruisecompany',
            name='order_number',
            field=models.PositiveBigIntegerField(default=app_main.models.get_order_number),
        ),
    ]
